######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2022 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The definition of a GitHub Issue Template.
##  COPYRIGHT   GPL-3.0
##  DATE        2022
##  FILE        bug.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: Bug Report
description: Outline a bug.
title: '[Bug] New Bug'
labels:
  - bug
assignees:
  - kevinmatthes
body:
  - type: markdown
    attributes:
      value: With this issue, a new bug is reported.
  - type: dropdown
    attributes:
      label: Version
      description: |
        Please specify the version of the software in which the bug occurred.
      options:
        - Nightly
        - v0.1.2
        - v0.1.1
        - v0.1.0
        - v0.1.0-rc1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Category
      description: |
        Please choose the category which describes best the bug to be reported.
      options:
        - Major — The software does not fulfill the task it is designed for.
        - Minor — The software basically does what it should do but there might
          be improvements.
        - Typo — There is a spelling mistake or something similar.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed Description
      description: |
        Please describe the bug in detail.  This is only required if the issue
        title is not alredy descriptive enough.  However, further details may be
        given by additional comments on this issue after its creation.
      placeholder: Detailed description of the bug
    validations:
      required: false

################################################################################
