######################## GNU General Public License 2.0 ########################
##                                                                            ##
## Copyright (C) 2022 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software; you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License along    ##
## with this program; if not, write to the Free Software Foundation, Inc.,    ##
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The definition of a GitHub Issue Template.
##  COPYRIGHT   GPL-2.0
##  DATE        2022
##  FILE        feature-request-new-alias.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: 'Feature Request:  New Alias'
description: Request a new Git alias command.
title: '[Feature Request] New Alias'
labels:
  - 'enhancement'
assignees:
  - kevinmatthes
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information in order to request a new Git
        alias command.
  - type: input
    attributes:
      label: Command Name
      description: Please suggest a name for the new alias.
      placeholder: Suggested alias name
    validations:
      required: true
  - type: input
    attributes:
      label: Definition
      description: Please specify how this alias shall be defined.
      placeholder: Definition of the new alias
    validations:
      required: true
  - type: input
    attributes:
      label: Description
      description: Please summarise briefly what this alias is supposed to do.
      placeholder: Brief description of the purpose
    validations:
      required: true

################################################################################
