######################## GNU General Public License 2.0 ########################
##                                                                            ##
## Copyright (C) 2022 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software; you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License along    ##
## with this program; if not, write to the Free Software Foundation, Inc.,    ##
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.                ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The definition of a GitHub Issue Template.
##  COPYRIGHT   GPL-2.0
##  DATE        2022
##  FILE        maintenance.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: 'Maintenance'
description: Request a maintenance of this project.
title: '[Maintenance] Maintenance Request'
labels:
  - 'maintenance'
assignees:
  - kevinmatthes
body:
  - type: markdown
    attributes:
      value: With this issue, a new maintenance is requested.
  - type: dropdown
    attrobutes:
      label: Type of the Maintenance
      description: |
        Please specify whether this is going to be a general or a pre-release
        maintenance.
      options:
        - General Maintenance
        - Pre-Release Maintenance
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Focus of the Maintenance
      description: |
        Which of the following features should be maintained in particular?
      options:
        - Everything.
        - The configured aliases.
        - The documentation of the aliases.
        - The documentation of the business logic.
        - The documentation of the repository.
        - The issue templates.
    validations:
      required: true
  - type: input
    attributes:
      label: Further Information
      description: At option, one may specify further information briefly here.
      placeholder: Is there anything to mind during the maintenance?
    validations:
      required: false

################################################################################
