name: New Alias
description: Request a new Git alias command.
title: '[Feature Request] New Alias'
labels: ['enhancement']
assignees:
  - kevinmatthes
body:
  - type: markdown
    attributes:
      value: This form is used in order request a new Git alias command.
  - type: input
    id: alias
    attributes:
      label: Command Name
      description: Please suggest a name for the new alias.
      placeholder: helloworld
    validations:
      required: true
  - type: input
    id: definition
    attributes:
      label: Definition
      description: Please specify how this alias shall be defined.
      placeholder: !echo Hello, World!
    validations:
      required: true
  - type: input
    id: comment
    attributes:
      label: Description
      description: Please summarise briefly what this alias is supposed to do.
      placeholder: Write 'Hello, World!' to `stdout`.
    validations:
      required: true
